services:
  db:
    image: nafama/mi_cine:v1
    container_name: MiCine
    environment:
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
      MYSQL_DATABASE: cine
      MYSQL_USER: usuario1
      MYSQL_PASSWORD: contrasenyaUsuario1
    ports:
      - "3307:3306"
  php:
    image: nafama/mi_app_cine:v1
    container_name: MiApp
    ports:
      - "8080:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: PhpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
    ports:
      - "8081:80"
    depends_on:
      - db